version: 0.2
phases:
  build:
    commands:
      - echo Building...
      - (cd authorizer && zip -r ../authorizer.zip .)
      - (cd manage && zip -r ../manage.zip .)
      - (cd remote_task && zip -r ../remote_task.zip .)
      - (cd task_control && zip -r ../task_control.zip .)
      - (cd task_result && zip -r ../task_result.zip .)
      - aws s3 cp authorizer.zip s3://$BUCKET
      - aws s3 cp manage.zip s3://$BUCKET
      - aws s3 cp remote_task.zip s3://$BUCKET
      - aws s3 cp task_control.zip s3://$BUCKET
      - aws s3 cp task_result.zip s3://$BUCKET
