version: 0.2
phases:
  build:
    commands:
      - echo Building...
      - (cd authorizer && zip -r ../authorizer.zip .)
      - openssl dgst -sha256 -binary authorizer.zip | openssl enc -base64 > authorizer.zip.base64sha256
      - (cd manage && zip -r ../manage.zip .)
      - openssl dgst -sha256 -binary manage.zip | openssl enc -base64 > manage.zip.base64sha256
      - (cd remote_task && zip -r ../remote_task.zip .)
      - openssl dgst -sha256 -binary remote_task.zip | openssl enc -base64 > remote_task.zip.base64sha256
      - (cd task_control && zip -r ../task_control.zip .)
      - openssl dgst -sha256 -binary task_control.zip | openssl enc -base64 > task_control.zip.base64sha256
      - (cd task_result && zip -r ../task_result.zip .)
      - openssl dgst -sha256 -binary task_result.zip | openssl enc -base64 > task_result.zip.base64sha256
      - aws s3 cp authorizer.zip s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key authorizer.zip --acl public-read
      - aws s3 cp --content-type text/plain authorizer.zip.base64sha256 s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key authorizer.zip.base64sha256 --acl public-read
      - aws s3 cp manage.zip s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key manage.zip --acl public-read
      - aws s3 cp --content-type text/plain manage.zip.base64sha256 s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key manage.zip.base64sha256 --acl public-read
      - aws s3 cp remote_task.zip s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key remote_task.zip --acl public-read
      - aws s3 cp --content-type text/plain remote_task.zip.base64sha256 s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key remote_task.zip.base64sha256 --acl public-read
      - aws s3 cp task_control.zip s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key task_control.zip --acl public-read
      - aws s3 cp --content-type text/plain task_control.zip.base64sha256 s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key task_control.zip.base64sha256 --acl public-read
      - aws s3 cp task_result.zip s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key task_result.zip --acl public-read
      - aws s3 cp --content-type text/plain task_result.zip.base64sha256 s3://$BUCKET
      - aws s3api put-object-acl --bucket $BUCKET --key task_result.zip.base64sha256 --acl public-read
      - echo Build complete.
