version: 0.2
phases:
  build:
    commands:
      - echo Building...
      - zip -rj authorizer.zip authorizer/.
      - zip -rj manage.zip manage/.
      - zip -rj remote_task.zip remote_task/.
      - zip -rj task_control.zip task_control/.
      - zip -rj task_result.zip task_result/.
      - aws s3 cp authorizer.zip s3://$BUCKET
      - aws s3 cp manage.zip s3://$BUCKET
      - aws s3 cp remote_task.zip s3://$BUCKET
      - aws s3 cp task_control.zip s3://$BUCKET
      - aws s3 cp task_result.zip s3://$BUCKET
